In [1]:
def print_integers_from_binary_file(file_path, start_line, end_line):
    """
    Reads integers from a binary file (assuming one integer per line) and prints the integers
    from start_line to end_line (inclusive).

    Parameters:
        file_path (str): Path to the binary file.
        start_line (int): The starting line number (1-based index).
        end_line (int): The ending line number (1-based index).
    """
    try:
        with open(file_path, 'rb') as binary_file:
            for current_line_number, line in enumerate(binary_file, start=1):
                if start_line <= current_line_number <= end_line:
                    try:
                        integer_value = int.from_bytes(line.strip(), byteorder='big', signed=True)
                        print(f"Line {current_line_number}: {integer_value}")
                    except ValueError:
                        print(f"Line {current_line_number}: Could not decode to integer")
                elif current_line_number > end_line:
                    break
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

In [2]:
import torch
import numpy as np
import random


seed = 44
##controling seeding
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)


def get_batch_random():
    data = train_data
    # ix = torch.randint(len(data) - block_size, (batch_size,))
    # Ensure the starting index is a multiple of block_size
    ix = torch.randint(0, len(data) // (block_size + 1), (batch_size,)) * (block_size + 1)
    print(ix)
    x = torch.stack([torch.from_numpy((data[i:i+block_size]).astype(np.int64)) for i in ix])
    y = torch.stack([torch.from_numpy((data[i+1:i+1+block_size]).astype(np.int64)) for i in ix])
    print(f'These are the first few lines of the batch: \n {x[0][0:10]}... \n {x[1][0:10]}... \n {x[2][0:10]}...')
    return x, y


def get_batch_index(a,b):
   # ix = torch.randint(len(data) - block_size, (batch_size,))
    # Ensure the starting index is a multiple of block_size
    ix = torch.tensor(range(a,b)) * (block_size + 1)
    x = torch.stack([torch.from_numpy((data[i:i+block_size]).astype(np.int64)) for i in ix])
    y = torch.stack([torch.from_numpy((data[i+1:i+1+block_size]).astype(np.int64)) for i in ix])
    return x, y

def write_tensor_to_file(tensor, output_path):
    """
    Writes a PyTorch tensor to a file in a single line.

    Parameters:
        tensor (torch.Tensor): The tensor to write to the file.
        output_path (str): Path to the output text file.
    """
    
    torch.set_printoptions(threshold=100000)
    try:
        with open(output_path, 'w') as output_file:
            for i in range(tensor.shape[0]):
                tensor_str = torch.flatten(tensor[i]).tolist()  # Flatten the tensor to 1D and convert to a list
                output_file.write(str(tensor_str) + '\n')  # Write the tensor as a single-line string
    except Exception as e:
        print(f"An error occurred: {e}")


In [3]:
file_path = 'data/trainrandom6gb.bin'  # Replace with the path to your binary file
train_data = np.memmap(file_path, dtype=np.uint8, mode='r')
block_size = 1023
batch_size = 4


x,y = get_batch_random()

tensor([2925971456, 3316672512,  284342272, 2370996224])
These are the first few lines of the batch: 
 tensor([15,  6,  4,  0, 27,  8,  0, 24, 11,  0])... 
 tensor([15,  6,  4,  0, 25,  9,  0, 24, 10,  0])... 
 tensor([15,  6,  4,  0, 24,  9,  0, 19, 30, 11])...


In [ ]:
x,y = get_batch_index(7891543,7891547)
output_file = "output.txt"
data = train_data
print(f"length of data is {len(data)}")
 

write_tensor_to_file(x,output_file)

In [7]:
# Example usage
file_path = 'data/trainrandom6gb.bin'  # Replace with the path to your binary file
start_line = 10  # Replace with the starting line number
end_line = 20    # Replace with the ending line number

print_lines_from_binary_file(file_path, start_line, end_line)

		


	





	

